### ISSUE TITLE
Backend refactoring 

### ISSUE THREAD

**Issue by beining00** [Visual-Testing-for-Android-Apps/backend#40]
## Problem1: Overcome the 6MB limit for live job video uploading 
For live job, we can only send videos with a size less than 6MB where most of the time a video is bigger than this. 
### Solution - use presign URL 
This approach will be similar to the batch job uploading approach. 
1. Frontend first requests a list of presign URLs from the backend  
```
//sample response 
{
    URLs: [{url: "url1", s3key:"s3key1"} , {url: "url2", s3key:"s3key2"}.... ]
}
```
2. Frontend uploads the video to S3 bucket directly with this URLs
3. Frontend involves seenomaly to for each files 
```
// sample request body
{
    s3key: "s3key1"
}
```
## Problem2: Continous deployment can is difficult to set up with the models files can't be pushed to the github repo
The to models files are too large to be pushed to the repo (seenomaly is 2GB). This makes the CD pipeline difficult the set up. 
### Solution 
Isolate the seenomaly and owleye models from other lambda components. At this moment, the seenomaly and owleye are in the same deployment script as other lambda functions. 
I think we can ...
* exclude seenomaly and owleye from the current deploy script 
* deploy them separately, and exclude them from the CD pipeline which we are going to build. 

To achieve this, we need to 
* generalise the behaviour of seenomaly and owleye. 
    * request body : an s3 bucket file location 
    * response : model inference 
* Batch job should also invoke the models through API requests.

New architecture illustration
![image](https://user-images.githubusercontent.com/55317028/133389570-04c5b465-5a6a-4c5a-9b5c-6164a83ab3db.png)

**Comment by idomo1** [comment]
**Problem 1**
This live job change would require more frontend work right? There's a lot of work to do for the rest of the semester, and I would rather not spend time on features which are already working if we don't have to. The videos being uploaded should be small anyway, since we only look at 8 frames of the video for the analysis. We can enforce a 6mb limit on the frontend pretty easily.
